version: '3.7'

services:

    redis:
        image: redis:alpine

    mysql:
        image: 'mysql:5.7'
        volumes:
            - './.:/tmp/host'
            - './.data/mysql:/var/lib/mysql'
        ports:
            - 3306:3306
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mmlit_vc
        logging:
            options:
                max-file: '10'
                max-size: '200k'

    app:
        build:
            context: .
        depends_on:
            - mysql
            - redis
        links:
            - mysql
            - redis
        volumes:
            - '.:/app'
            - './.server-configs/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
        ports:
            - "8000:8000"
        logging:
            options:
                max-file: '10'
                max-size: '200k'
