version: '3.7'

services:
    memcached:
        image: memcached:alpine
        ports:
            - '11211:11211'
        entrypoint:
            - memcached
            - -m 64
        logging:
            options:
                max-file: '10'
                max-size: '200k'

    mysql:
        image: 'mysql:5.7'
        volumes:
            - './.:/tmp/host'
            - './.data/mysql:/var/lib/mysql'
        ports:
            - 3306:3306
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mmlit_vc
        logging:
            options:
                max-file: '10'
                max-size: '200k'

    app:
        build:
            context: .
        depends_on:
            - mysql
            - memcached
        links:
            - mysql
            - memcached
        volumes:
            - '.:/app'
        ports:
            - "8000:8000"
        logging:
            options:
                max-file: '10'
                max-size: '200k'
